### ISSUE TITLE
Line separation with <br> tag keeps ">" after applying render()

### ISSUE THREAD

**Issue by askarimov** [malcommac/SwiftRichString#21] opened 2017-07-08 14:26 UTC
Hi,

I was trying to create an attributed string from this:
`"<p><b>5 July</b><br>- It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.<br>- of the printing and typesetting industry. Lorem Ipsum has been the industry's </p>".`

with the following code:
let style = Style.default {
                $0.font = FontAttribute(.HelveticaNeue_Light, size: 16)
                $0.color =  ColorPalette.turquoiseBlue
            }
let parser = MarkupString(source: news.subtitle, styles: [style])!
let attributedText = parser.render()

The result that I am getting is like this: 
`"...>- It is a long established..."`

Dont know if its a bug or I am doing something wrong.

**Comment by simonboriis** [comment] 2017-11-16 08:33
Looks like the issue is the use of continue here `					if var tag = Tag(raw: rawTag) {
						if tag.name == "br" { // it's a return carriage, we want to translate it directly
							plainText += "\n"
							continue
						}`

**Comment by malcommac** [comment] 2017-12-28 10:33
Merged into master (cocoapods version is 1.1.0 just released)

**Closed** 2017-12-28 10:33 UTC
Labels: bug
