### ISSUE TITLE
Support to insert images on text using NSTextAttachament

### ISSUE THREAD

**Issue by unnamedd** [malcommac/SwiftRichString#6] opened 2017-03-06 15:30 UTC
I believe that support NSTextAttachment image could be a good feature to have on lib

**Comment by unnamedd** [comment] 2017-03-06 15:36
Sorry. I found on [Style.swift](https://github.com/malcommac/SwiftRichString/blob/master/Sources/Style.swift#L362) support to NSTextAttachment, but on README.

**Comment by Jauzee** [comment] 2017-09-26 03:47
Didn't want to open new issue, since is will the duplicate of this one.

I'm unable to get it to work. I create a Style, set an attach with an image, apply to the text and nothing changes there. Used default implementation for now, but wanted to get rid off that.

@unnamedd did you get able to set an attachment?

**Comment by unnamedd** [comment] 2017-09-26 08:21
Hi, @Jauzee

here you can find a post explaining how to use NSTextAttachment to AttributedString:
https://www.hackingwithswift.com/example-code/system/how-to-insert-images-into-an-attributed-string-with-nstextattachment

here is where SwiftRichString works NSTextAttachments:
https://github.com/malcommac/SwiftRichString/blob/f53e928872dcf445d7bd51520554c2fd6717c558/Sources/SwiftRichString/Style.swift#L403

Here is some example that could work for you. I didn't test this piece of code, so it's by yourself, if you have another question, just comment here again.

```swift
// create our NSTextAttachment
let image1Attachment = NSTextAttachment()
image1Attachment.image = UIImage(named: "yourIcon.png")

// create our valueStyle 
let valueStyle = Style("value", {
    $0.font = FontAttribute(.HelveticaNeue_Bold, size: 18)
    $0.color = UIColor(red: 85/255, green: 85/255, blue: 85/255, alpha: 1)
    $0.align = .center
    $0.attach = image1Attachment
})
```

**Comment by mukyasa** [comment] 2017-12-18 06:38
Hello ,

Did anyone find the solution to add `NSTextAttachment` i am facing difficulty adding it.

**Comment by GabrielCartier** [comment] 2019-04-22 18:27
> Hello ,
> 
> Did anyone find the solution to add `NSTextAttachment` i am facing difficulty adding it. The above solution didn't work for me

A bit late, but the key is to add your attachment to your `NSAttributedString`. The code given does not work indeed. Something like this would work:
```
let imageAttachment = NSTextAttachment()
imageAttachment.image = UIImage(named: "your_image")
let attributedString = NSMutableAttributedString(attachment: imageAttachment)
attributedString.append(NSAttributedString(string: "your text"))
```

Then you can simply apply the style you want on the `AttributedString`

**Closed** 2019-12-21 23:40 UTC
Labels: enhancement
